add smoke

diff --git a/.github/workflows/smoke.yml b/.github/workflows/smoke.yml
--- a/.github/workflows/smoke.yml
+++ b/.github/workflows/smoke.yml
@@ -59,5 +59,11 @@ jobs:
       - name: Check smoke
         run: |
           kubectl get pod -n vanus | grep quick-display | awk '{print $1}' | xargs kubectl logs -n vanus | grep -n "total" | wc -l
-          # [[ $(kubectl get pod -n vanus | grep quick-display | awk '{print $1}' | xargs kubectl logs -n vanus | grep -n "total" | wc -l) -eq 10001 ]] && echo "success" || echo "failed"
+          echo sleep5s
+          sleep 5s
+          kubectl get pod -n vanus | grep quick-display | awk '{print $1}' | xargs kubectl logs -n vanus | grep -n "total" | wc -l
+          echo sleep5s
+          sleep 5s
+          kubectl get pod -n vanus | grep quick-display | awk '{print $1}' | xargs kubectl logs -n vanus | grep -n "total" | wc -l
+          [[ $(kubectl get pod -n vanus | grep quick-display | awk '{print $1}' | xargs kubectl logs -n vanus | grep -n "total" | wc -l) -eq 4 ]] && echo "success" || echo "failed"
 
